# Generated by Django 5.1.6 on 2025-02-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_alter_elementdemodule_unique_together_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monapp.classe'),
        ),
        migrations.CreateModel(
            name='CoursClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_classes', to='monapp.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_classes', to='monapp.elementdemodule')),
            ],
            options={
                'verbose_name': 'Association Cours-Classe',
                'verbose_name_plural': 'Associations Cours-Classes',
                'unique_together': {('cours', 'classe')},
            },
        ),
    ]
