# Generated by Django 5.1.6 on 2025-03-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_etudiant_classe_coursclasse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elementdemodule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='elementdemodule',
            name='classes',
            field=models.ManyToManyField(through='monapp.CoursClasse', to='monapp.classe'),
        ),
        migrations.AddField(
            model_name='elementdemodule',
            name='volumeHoraireSemestre',
            field=models.IntegerField(help_text='Volume horaire total pour le semestre', null=True),
        ),
        migrations.AlterField(
            model_name='coursclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.classe'),
        ),
        migrations.AlterField(
            model_name='coursclasse',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.elementdemodule'),
        ),
        migrations.AlterField(
            model_name='elementdemodule',
            name='volumeHoraire',
            field=models.IntegerField(help_text='Volume horaire par session de cours'),
        ),
    ]
