# Generated by Django 5.1.6 on 2025-03-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_alter_nondisponibilite_options_nondisponibilite_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nondisponibilite',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
